"""Database preparation package."""

from __future__ import annotations

from odoo_instance_sdk.internal.dbprep.materialize import (
    DatabasePreparationCoordinator,
    preflight_restore,
    prepare_download,
    prepare_restore,
)
from odoo_instance_sdk.internal.dbprep.materialize_steps import _preparation_process_steps
from odoo_instance_sdk.internal.dbprep.source import (
    DatabasePreparationFailureContext,
    ProjectRuntimeBinding,
    RestorePreflight,
    _CatalogueRestoreSource,
    _LocalArchiveRestoreSource,
    _open_verified_zip,
    _planned_project_identity,
    build_selected_backup_restore_steps,
    canonical_project_identity,
    capture_local_archive_restore,
    capture_selected_backup_restore,
    classify_freshness,
    cleanup_selected_backup_restore,
    compare_provenance,
    generate_target_database,
    materialize_selected_backup_dump,
    materialize_selected_backup_filestore,
    preparation_lock,
    relevant_manifest_conflicts,
    reserve_target_database,
    resolve_remote_database_name,
    resolve_runtime_binding,
    resolve_test_source,
)
from odoo_instance_sdk.internal.dbprep.source_binding import (
    _catalogue_backup_preflight,
    _manifest_after_preparation,
    build_target_instance,
)

__all__ = [
    "DatabasePreparationCoordinator",
    "DatabasePreparationFailureContext",
    "ProjectRuntimeBinding",
    "RestorePreflight",
    "_CatalogueRestoreSource",
    "_LocalArchiveRestoreSource",
    "_catalogue_backup_preflight",
    "_manifest_after_preparation",
    "_open_verified_zip",
    "_planned_project_identity",
    "_preparation_process_steps",
    "build_selected_backup_restore_steps",
    "build_target_instance",
    "canonical_project_identity",
    "capture_local_archive_restore",
    "capture_selected_backup_restore",
    "classify_freshness",
    "cleanup_selected_backup_restore",
    "compare_provenance",
    "generate_target_database",
    "materialize_selected_backup_dump",
    "materialize_selected_backup_filestore",
    "preflight_restore",
    "preparation_lock",
    "prepare_download",
    "prepare_restore",
    "relevant_manifest_conflicts",
    "reserve_target_database",
    "resolve_remote_database_name",
    "resolve_runtime_binding",
    "resolve_test_source",
]
