"""Compatibility exports for the neutral real-Odoo pin contract."""

from scripts.real_odoo_pins import (
    E2E_PINS,
    FAILURE_BUNDLE_LIMIT_BYTES,
    PHASE_BUDGETS,
    PLATFORM_IMAGE_MANIFESTS,
    SUCCESS_ARTIFACT_LIMIT_BYTES,
    CacheClass,
    E2EPinManifest,
    PhaseBudget,
    PrerequisiteError,
    Tier,
    budget_for,
    classify_cache,
    current_platform,
    normalize_platform,
    pin_manifest_dict,
    prerequisite_manifest,
    require_prerequisites,
    validate_pins,
    validate_platform,
)

__all__ = [
    "E2E_PINS",
    "FAILURE_BUNDLE_LIMIT_BYTES",
    "PHASE_BUDGETS",
    "PLATFORM_IMAGE_MANIFESTS",
    "SUCCESS_ARTIFACT_LIMIT_BYTES",
    "CacheClass",
    "E2EPinManifest",
    "PhaseBudget",
    "PrerequisiteError",
    "Tier",
    "budget_for",
    "classify_cache",
    "current_platform",
    "normalize_platform",
    "pin_manifest_dict",
    "prerequisite_manifest",
    "require_prerequisites",
    "validate_pins",
    "validate_platform",
]
