"""Odoo Instance SDK — typed Python API for managing local Odoo 19.0 instances."""

import odoo_instance_sdk.models as _models
from odoo_instance_sdk.client import OdooClient
from odoo_instance_sdk.config import InstanceConfig, OdooClientConfig
from odoo_instance_sdk.exceptions import (
    BackupCatalogError,
    BackupDownloadError,
    BackupNotAvailableError,
    BackupNotFoundError,
    BackupValidationUnavailableError,
    CommandTimeoutError,
    ConfigError,
    DatabaseAlreadyExistsError,
    DatabaseError,
    DatabaseManagerUnavailableError,
    DropFailedError,
    EnvironmentConflictError,
    EnvironmentNotFoundError,
    EnvironmentResolutionError,
    InstanceConfigurationError,
    InvalidBaseUrlError,
    LockConflictError,
    MasterPasswordRequiredError,
    MonitorError,
    MonitorExtrasMissingError,
    NonLocalInstanceError,
    OdooInstanceSdkError,
    PostgresClusterError,
    PostgresClusterNotOwnedError,
    PostgresClusterStartError,
    PostgresClusterStopError,
    PostgresClusterTimeoutError,
    PostgresClusterUnhealthyError,
    PostgresClusterUnreachableError,
    PostgresComposeInvalidError,
    PostgresComposeUnavailableError,
    PostgresImageNotTrustedError,
    PostgresPortCollisionError,
    ProcessExitedBeforeReady,
    ProcessNotFoundError,
    ProjectContextError,
    ProjectManifestNotFoundError,
    ReadinessTimeoutError,
    RestoreFailedError,
    VscodeImportError,
)
from odoo_instance_sdk.models import (
    Backup,
    BackupDeletionResult,
    BackupEvent,
    BackupEventType,
    BackupFormat,
    BackupState,
    BackupValidationResult,
    BackupValidationStatus,
    ClusterContainer,
    ClusterEndpoint,
    ClusterMetrics,
    ClusterResourceSnapshot,
    ClusterSnapshot,
    CommandResult,
    Database,
    DatabaseFootprint,
    DropResult,
    EnvironmentSnapshot,
    GitActivity,
    GitActivityState,
    GitDiff,
    NoBackup,
    OdooProcess,
    PidScope,
    PostgresClusterState,
    ProcessStatus,
    ProjectSummary,
    PythonEnvFootprint,
    ReadinessResult,
    RestoreResult,
    RuntimeMetrics,
    RuntimeState,
    Snapshot,
    StartConfig,
    StorageFootprint,
)
from odoo_instance_sdk.project import PostgresProjectConfig, ProjectConfig
from odoo_instance_sdk.resources.backup import BackupResource
from odoo_instance_sdk.resources.database import DatabaseResource
from odoo_instance_sdk.resources.environment import (
    DevelopmentEnvironment,
    EnvironmentCheckoutOptions,
    EnvironmentDatabaseMode,
    EnvironmentResource,
    EnvironmentState,
)
from odoo_instance_sdk.resources.instance import InstanceFactory, OdooInstance
from odoo_instance_sdk.resources.postgres import PostgresCluster

# ponytail: populate models module globals so msgspec can resolve the string
# annotation "EnvironmentState" on EnvironmentSnapshot at encode time; a real
# import in models.py would create a cycle (resources.environment -> models).
_models.EnvironmentState = EnvironmentState  # type: ignore[attr-defined]

__version__ = "0.1.0"
__all__ = [
    "Backup",
    "BackupCatalogError",
    "BackupDeletionResult",
    "BackupDownloadError",
    "BackupEvent",
    "BackupEventType",
    "BackupFormat",
    "BackupNotAvailableError",
    "BackupNotFoundError",
    "BackupResource",
    "BackupState",
    "BackupValidationResult",
    "BackupValidationStatus",
    "BackupValidationUnavailableError",
    "ClusterContainer",
    "ClusterEndpoint",
    "ClusterMetrics",
    "ClusterResourceSnapshot",
    "ClusterSnapshot",
    "CommandResult",
    "CommandTimeoutError",
    "ConfigError",
    "Database",
    "DatabaseAlreadyExistsError",
    "DatabaseError",
    "DatabaseFootprint",
    "DatabaseManagerUnavailableError",
    "DatabaseResource",
    "DevelopmentEnvironment",
    "DropFailedError",
    "DropResult",
    "EnvironmentCheckoutOptions",
    "EnvironmentConflictError",
    "EnvironmentDatabaseMode",
    "EnvironmentNotFoundError",
    "EnvironmentResolutionError",
    "EnvironmentResource",
    "EnvironmentSnapshot",
    "EnvironmentState",
    "GitActivity",
    "GitActivityState",
    "GitDiff",
    "InstanceConfig",
    "InstanceConfigurationError",
    "InstanceFactory",
    "InvalidBaseUrlError",
    "LockConflictError",
    "MasterPasswordRequiredError",
    "MonitorError",
    "MonitorExtrasMissingError",
    "NoBackup",
    "NonLocalInstanceError",
    "OdooClient",
    "OdooClientConfig",
    "OdooInstance",
    "OdooInstanceSdkError",
    "OdooProcess",
    "PidScope",
    "PostgresCluster",
    "PostgresClusterError",
    "PostgresClusterNotOwnedError",
    "PostgresClusterStartError",
    "PostgresClusterState",
    "PostgresClusterStopError",
    "PostgresClusterTimeoutError",
    "PostgresClusterUnhealthyError",
    "PostgresClusterUnreachableError",
    "PostgresComposeInvalidError",
    "PostgresComposeUnavailableError",
    "PostgresImageNotTrustedError",
    "PostgresPortCollisionError",
    "PostgresProjectConfig",
    "ProcessExitedBeforeReady",
    "ProcessNotFoundError",
    "ProcessStatus",
    "ProjectConfig",
    "ProjectContextError",
    "ProjectManifestNotFoundError",
    "ProjectSummary",
    "PythonEnvFootprint",
    "ReadinessResult",
    "ReadinessTimeoutError",
    "RestoreFailedError",
    "RestoreResult",
    "RuntimeMetrics",
    "RuntimeState",
    "Snapshot",
    "StartConfig",
    "StorageFootprint",
    "VscodeImportError",
]
