"""Odoo Instance SDK — typed Python API for managing local Odoo 19.0 instances."""

from odoo_instance_sdk.client import OdooClient
from odoo_instance_sdk.config import InstanceConfig, OdooClientConfig
from odoo_instance_sdk.exceptions import (
    BackupCatalogError,
    BackupDownloadError,
    BackupNotAvailableError,
    BackupNotFoundError,
    BackupValidationUnavailableError,
    CommandTimeoutError,
    ConfigError,
    DatabaseAlreadyExistsError,
    DatabaseError,
    DatabaseManagerUnavailableError,
    DropFailedError,
    InstanceConfigurationError,
    InvalidBaseUrlError,
    MasterPasswordRequiredError,
    NonLocalInstanceError,
    OdooInstanceSdkError,
    ProcessExitedBeforeReady,
    ProcessNotFoundError,
    ReadinessTimeoutError,
    RestoreFailedError,
)
from odoo_instance_sdk.models import (
    Backup,
    BackupDeletionResult,
    BackupEvent,
    BackupEventType,
    BackupFormat,
    BackupState,
    BackupValidationResult,
    BackupValidationStatus,
    CommandResult,
    Database,
    DropResult,
    NoBackup,
    OdooProcess,
    ProcessStatus,
    ReadinessResult,
    RestoreResult,
    StartConfig,
)
from odoo_instance_sdk.resources.backup import BackupResource
from odoo_instance_sdk.resources.database import DatabaseResource
from odoo_instance_sdk.resources.instance import InstanceFactory, OdooInstance

__version__ = "0.1.0"
__all__ = [
    "Backup",
    "BackupCatalogError",
    "BackupDeletionResult",
    "BackupDownloadError",
    "BackupEvent",
    "BackupEventType",
    "BackupFormat",
    "BackupNotAvailableError",
    "BackupNotFoundError",
    "BackupResource",
    "BackupState",
    "BackupValidationResult",
    "BackupValidationStatus",
    "BackupValidationUnavailableError",
    "CommandResult",
    "CommandTimeoutError",
    "ConfigError",
    "Database",
    "DatabaseAlreadyExistsError",
    "DatabaseError",
    "DatabaseManagerUnavailableError",
    "DatabaseResource",
    "DropFailedError",
    "DropResult",
    "InstanceConfig",
    "InstanceConfigurationError",
    "InstanceFactory",
    "InvalidBaseUrlError",
    "MasterPasswordRequiredError",
    "NoBackup",
    "NonLocalInstanceError",
    "OdooClient",
    "OdooClientConfig",
    "OdooInstance",
    "OdooInstanceSdkError",
    "OdooProcess",
    "ProcessExitedBeforeReady",
    "ProcessNotFoundError",
    "ProcessStatus",
    "ReadinessResult",
    "ReadinessTimeoutError",
    "RestoreFailedError",
    "RestoreResult",
    "StartConfig",
]
